services:
  app:
    build: .
    container_name: send-mailer-app
    environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/sendmailerapp
    - NODE_ENV=development
    - PORT=5003
    ports: 
      - "5003:5003"
    depends_on:
      - db
    volumes:
     - .:/app
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sendmailerapp
    ports:
      - "5500:5500"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:   


